### ISSUE TITLE
Can't generate nested scaffold

### ISSUE THREAD

**Issue by u2** [benignware/scaffold_assoc#1]
`rails g scaffold_assoc Team/Membership user_id:integer role:integer`

```
/Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/scaffold_assoc-685253b1fed1/lib/generators/scaffold_assoc/scaffold_assoc_generator.rb:38:in `create_migration': wrong number of arguments (3 for 0) (ArgumentError)
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/generators/migration.rb:63:in `migration_template'
    from /Users/u2/.rvm/gems/ruby-2.1.2/bundler/gems/scaffold_assoc-685253b1fed1/lib/generators/scaffold_assoc/scaffold_assoc_generator.rb:42:in `create_migration'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/generators.rb:157:in `invoke'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/commands/generate.rb:11:in `<top (required)>'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:135:in `generate_or_destroy'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:51:in `generate'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
    from /Users/u2/.rvm/gems/ruby-2.1.2/gems/railties-4.1.9/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by u2** [comment]
Thanks.
